services:
  # Le service de la base de données
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27019:27017"
    environment:
      # REMPLACÉ : on utilise des variables pour la sécurité
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    command: mongod --auth
    volumes:
      - mongo_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - medic_network # AJOUTÉ : Connexion au réseau isolé

  # Le service qui lance le script de migration
  migration:
    build: .
    container_name: migration_script_container
    depends_on:
      - mongodb
    environment:
      # On passe aussi les identifiants au script Python
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    volumes:
      - .:/app
    networks:
      - medic_network # AJOUTÉ : Connexion au même réseau

volumes:
  mongo_data:

# AJOUTÉ : Définition du réseau privé
networks:
  medic_network:
    driver: bridge